import React from "react";
export const metadata = {
  title: "Product Page",
  description: "Generated by Dr. Vipin Classes",
};

const page = () => {
  return <div>Product Page</div>;
};

export default page;
