export const metadata = {
  title: "Dr. Vipin Classes",
  description: "Generated by Dr. Vipin Kumar",
};
export default function Home() {
  return (
    <main className="container">
      <h2>Dr. Vipin Classes</h2>      
    </main>
  );
}
